rules:
  class-name-format:
    - 0
  force-attribute-nesting:
    - 0
  force-element-nesting:
    - 0
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-color-literals:
    - 0
  no-vendor-prefixes:
    - 0
  no-qualifying-elements:
    - 1
    -  
      allow-element-with-attribute: true
      allow-element-with-class: true
